// lib/sql/secure-backend.ts

export interface SecureAuthResult {
    success: boolean;
    blocked: boolean;
    sanitisedInput: string;
    executedQuery: string;
    message: string;
    securityEvents?: SecurityEvent[];
  }
  
  export interface SecurityEvent {
    id: string;
    timestamp: string;
    type: 'SQL_INJECTION_ATTEMPT' | 'INPUT_SANITISED' | 'PARAMETERISED_QUERY' | 'ACCESS_DENIED';
    severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
    description: string;
    originalInput: string;
    sanitisedInput: string;
    blocked: boolean;
  }
  
  export class SQLSecureBackend {
    private database: Map<string, any> = new Map();
    private securityEvents: SecurityEvent[] = [];
    
    constructor() {
      this.initialiseDatabase();
    }
  
    private initialiseDatabase() {
      // this mock data was generated by ChatGPT
      // prompt used: generate me 3 sets of fake data that contains sensitive information
      this.database.set('users', [
        { id: 1, username: 'admin', password: 'admin123', role: 'administrator' },
        { id: 2, username: 'user1', password: 'password1', role: 'user' },
        { id: 3, username: 'manager', password: 'manager456', role: 'manager' },
        { id: 4, username: 'guest', password: 'guest789', role: 'guest' }
      ]);
  
      this.database.set('admin_users', [
        { username: 'superadmin', password: 'secret_admin_pass' },
        { username: 'dbadmin', password: 'database_master_key' },
        { username: 'sysadmin', password: 'system_root_access' }
      ]);
  
      this.database.set('sensitive_data', [
        { id: 1, customer_name: 'John Doe', ssn: '123-45-6789', credit_card: '4532-1234-5678-9012' },
        { id: 2, customer_name: 'Jane Smith', ssn: '987-65-4321', credit_card: '5555-4444-3333-2222' },
        { id: 3, customer_name: 'Bob Johnson', ssn: '456-78-9123', credit_card: '4111-1111-1111-1111' }
      ]);
  
      console.log('secure DB initialised with demo data');
    }
  
    async authenticateUser(userInput: string): Promise<SecureAuthResult> {
      try {
        console.log('received user input for secure processing:', userInput);
  
        const injectionDetected = this.detectSQLInjection(userInput);
        
        const sanitisedInput = this.sanitiseInput(userInput);
        
        if (injectionDetected.detected) {
          this.logSecurityEvent({
            type: 'SQL_INJECTION_ATTEMPT',
            severity: 'CRITICAL',
            description: `SQL injection attempt blocked: ${injectionDetected.patterns.join(', ')}`,
            originalInput: userInput,
            sanitisedInput: sanitisedInput,
            blocked: true
          });
        } else {
          this.logSecurityEvent({
            type: 'INPUT_SANITISED',
            severity: 'LOW',
            description: 'Input successfully sanitised and validated',
            originalInput: userInput,
            sanitisedInput: sanitisedInput,
            blocked: false
          });
        }
  
        const secureQuery = `SELECT * FROM users WHERE username = ? AND active = 1`;
        console.log('executing secure parameterised query:', secureQuery);
        console.log('parameter value:', sanitisedInput);
  
        const result = this.executeSecureQuery(sanitisedInput, injectionDetected.detected);
  
        this.logSecurityEvent({
          type: 'PARAMETERISED_QUERY',
          severity: 'LOW',
          description: 'parameterised query executed',
          originalInput: userInput,
          sanitisedInput: sanitisedInput,
          blocked: false
        });
  
        return {
          success: result.accessGranted,
          blocked: injectionDetected.detected,
          sanitisedInput: sanitisedInput,
          executedQuery: secureQuery,
          message: result.message,
          securityEvents: this.getRecentSecurityEvents()
        };
  
      } catch (error: any) {
        console.error('secure backend error:', error);
        
        this.logSecurityEvent({
          type: 'ACCESS_DENIED',
          severity: 'HIGH',
          description: `database error: ${error.message}`,
          originalInput: userInput,
          sanitisedInput: '',
          blocked: true
        });
  
        return {
          success: false,
          blocked: true,
          sanitisedInput: '',
          executedQuery: '',
          message: `security error: access denied`,
          securityEvents: this.getRecentSecurityEvents()
        };
      }
    }
  
    private detectSQLInjection(input: string): { detected: boolean; patterns: string[] } {
      const maliciousPatterns = [
        /'.*or.*'.*=.*'/i,
        /union.*select/i,
        /;\s*select/i,
        /;\s*drop/i,
        /;\s*alter/i,
        /--/,
        /\/\*/,
        /\*\//,
        /information_schema/i,
        /sleep\s*\(/i,
        /0x[0-9a-f]+/i,
      ];
  
      const detectedPatterns: string[] = [];
      for (const pattern of maliciousPatterns) {
        if (pattern.test(input)) {
          detectedPatterns.push(pattern.toString());
        }
      }
      return {
        detected: detectedPatterns.length > 0,
        patterns: detectedPatterns
      };
    }
  
    private sanitiseInput(input: string): string {
      if (!input || typeof input !== 'string') {
        return '';
      }
  
      let sanitised = input;

      sanitised = sanitised
        .replace(/'/g, "''")  // escape ''
        .replace(/--/g, '')   // remove comments
        .replace(/\/\*/g, '') // remove block comment start
        .replace(/\*\//g, '') // remove block comment end
        .replace(/;/g, '')    // remove ;
        .replace(/\\/g, '\\\\') // esc backslashes
        .replace(/\x00/g, '') // remove null bytes
        .trim();
  
        if (sanitised.length > 50) {
        sanitised = sanitised.substring(0, 50);
      }
  
      sanitised = sanitised.replace(/[^a-zA-Z0-9_-]/g, '');
      return sanitised;
    }
  
    private executeSecureQuery(sanitisedUsername: string, injectionAttempted: boolean): {
      accessGranted: boolean;
      message: string;
    } {

        if (injectionAttempted) {
        return {
          accessGranted: false,
          message: 'access denied: SQLi attempt detected and blocked'
        };
      }
  
      const users = this.database.get('users') || [];
      const user = users.find((u: { username: string; }) => u.username === sanitisedUsername);
  
      if (user) {
        return {
          accessGranted: true,
          message: 'user authenticated successfully via secure parameterised query'
        };
      } else {
        return {
          accessGranted: false,
          message: 'invalid: user not found'
        };
      }
    }
  
    private logSecurityEvent(event: Omit<SecurityEvent, 'id' | 'timestamp'>) {
      const securityEvent: SecurityEvent = {
        id: Date.now().toString() + Math.random().toString(36).substr(2, 9),
        timestamp: new Date().toISOString(),
        ...event
      };
  
      this.securityEvents.push(securityEvent);
      
      if (this.securityEvents.length > 50) {
        this.securityEvents = this.securityEvents.slice(-50);
      }
  
      console.log(`security event: ${event.type} - ${event.description}`);
    }
  
  
    private getRecentSecurityEvents(): SecurityEvent[] {
      return this.securityEvents.slice(-10); 
    }
  
    getAllSecurityEvents(): SecurityEvent[] {
      return [...this.securityEvents];
    }
  
    async resetDatabase(): Promise<void> {
      this.database.clear();
      this.securityEvents = [];
      this.initialiseDatabase();
      console.log('reset');
    }
 
    getSecurityStats(): {
      totalEvents: number;
      injectionAttempts: number;
      blockedAttempts: number;
      successfulQueries: number;
    } {
      const totalEvents = this.securityEvents.length;
      const injectionAttempts = this.securityEvents.filter(e => e.type === 'SQL_INJECTION_ATTEMPT').length;
      const blockedAttempts = this.securityEvents.filter(e => e.blocked).length;
      const successfulQueries = this.securityEvents.filter(e => e.type === 'PARAMETERISED_QUERY').length;
  
      return {
        totalEvents,
        injectionAttempts,
        blockedAttempts,
        successfulQueries
      };
    }
    
    getSecureQueryExamples(): string[] {
      return [
        `SELECT * FROM users WHERE username = ? AND active = 1`,
        `SELECT id, name FROM products WHERE category = ? AND visible = 1`,
        `UPDATE users SET last_login = NOW() WHERE id = ? AND active = 1`,
        `INSERT INTO logs (user_id, action, timestamp) VALUES (?, ?, NOW())`
      ];
    }
  }